services:
  # Backend API Service
  - type: web
    name: digit-recognition-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7

  # Frontend Static Site
  - type: web
    name: digit-recognition-frontend
    env: static
    buildCommand: cd digit-frontend && npm ci && REACT_APP_API_URL=https://digit-recognition-api.onrender.com npm run build
    staticPublishPath: ./digit-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 